class ImageAssets {
  static const logo = "assets/images/logo.png";
  static const splashBg = "assets/images/splash_bg.png";
  static const firstMenuBg = "assets/images/first_menu_bg.png";
  static const loginBg = "assets/images/login_bg.png";
  static const userAppbar = "assets/images/user_appbar_image.png";
  static const meassageUnRead = "assets/images/meassage_unread.png";
  static const meassageRead = "assets/images/meassage_read.png";
  static const vipCard = "assets/images/vip_card.png";
  static const fadeOutBg = "assets/images/fade_out_bg.png";
  static const successBg = "assets/images/sucess_bg.png";
  static const h1ForgotPass = "assets/images/h1_forgot_pass.png";
  static const defaultImage = "assets/images/default_image.png";
  static const giftCard = "assets/images/gift_card.png";
  ImageAssets._();
}

class IconAssets {
  static const eye = "assets/icons/eye_icon.png";
  static const lock = "assets/icons/lock_icon.png";
  static const person = "assets/icons/person_icon.png";
  static const bestSell = "assets/icons/best_sell_icon.png";
  static const recommend = "assets/icons/recommend_icon.png";
  static const promotion = "assets/icons/promotion_icon.png";
  static const home = "assets/icons/home_icon.png";
  static const message = "assets/icons/message_icon.png";
  static const setting = "assets/icons/setting_icon.png";
  static const shop = "assets/icons/shop_icon.png";
  static const homeFill = "assets/icons/home_icon_fill.png";
  static const messageFill = "assets/icons/message_icon_fill.png";
  static const settingFill = "assets/icons/setting_icon_fill.png";
  static const shopFill = "assets/icons/shop_icon_fill.png";
  static const transportFill = "assets/icons/transport_icon_fill.png";
  static const transport = "assets/icons/transport_icon.png";
  static const colorsWatch = "assets/icons/colorswatch_icon.png";
  static const bagHappy = "assets/icons/baghappy_icon.png";
  static const moneySend = "assets/icons/moneysend_icon.png";
  static const clock = "assets/icons/clock.png";
  static const minus = "assets/icons/minus_icon.png";
  static const plusCirlce = "assets/icons/plus_circle_icon.png";
  static const trashCan = "assets/icons/trash_can_icon.png";
  static const locationTick = "assets/icons/locationtick_icon.png";
  static const briefCase = "assets/icons/briefcase_icon.png";
  static const personalCard = "assets/icons/personalcard_icon.png";
  static const walleTadd1 = "assets/icons/walletadd1_icon.png";
  static const homeHashtag = "assets/icons/homehashtag_icon.png";
  static const arrowDown = "assets/icons/arrow_down_icon.png";
  static const close = "assets/icons/close_icon.png";
  static const bitcoinCard = "assets/icons/bitcoincard_icon.png";
  static const attachCircle = "assets/icons/attachcircle_icon.png";
  static const userTick = "assets/icons/usertick_icon.png";
  static const attachFile = "assets/icons/attach_file_icon.png";
  static const check = "assets/icons/check_icon.png";
  static const closeCircle = "assets/icons/closecircle_icon.png";
  static const search = "assets/icons/search_icon.png";
  static const arrowRight = "assets/icons/arrow_right_icon.png";
  static const plus = "assets/icons/plus_icon.png";
  static const trashRed = "assets/icons/trash_red_icon.png";
  static const pending = "assets/icons/pending_icon.png";
  static const delivered = "assets/icons/delivered_icon.png";
  static const tickCircle = "assets/icons/tick_circle_icon.png";
  static const clockRed = "assets/icons/clock_red_icon.png";
  static const userSquare = "assets/icons/usersquare_icon.png";
  static const securityUser = "assets/icons/securityuser_icon.png";
  static const gift = "assets/icons/gift_icon.png";
  static const edit = "assets/icons/edit_icon.png";
  static const mobile = "assets/icons/mobile_icon.png";
  IconAssets._();
}
